name: Code Quality Checks

on:
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  code-quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set Up pixi Environment
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.28.2
      - name: Restore pre-commit Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: pre-commit
          save-always: true
      - name: Run pre-commit on All Files
        run: |
          pixi run pre-commit run \
          --show-diff-on-failure \
          --color=always \
          --all-files
      - name: Suggest Code Changes
        if: (success() || failure()) && github.event_name == 'pull_request'
        uses: reviewdog/action-suggester@v1
