name: Terraform Plan and Apply AWS Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'aws_infrastructure/**'
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'aws_infrastructure/**'
  workflow_dispatch:

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: aws_infrastructure

      - name: Terraform Plan
        run: terraform plan -out=aws_infrastructure.tfplan
        working-directory: aws_infrastructure

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: aws_infrastructure.tfplan
          path: aws_infrastructure/aws_infrastructure.tfplan

  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: aws_infrastructure.tfplan
          path: aws_infrastructure

      - name: Terraform Init
        run: terraform init
        working-directory: aws_infrastructure

      - name: Terraform Apply
        run: terraform apply aws_infrastructure.tfplan
        working-directory: aws_infrastructure
