name: Terraform Plan and Apply Airbyte

on:
  push:
    branches:
      - main
    paths:
      - 'airbyte_extract_load/**'
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'airbyte_extract_load/**'
  workflow_dispatch:

jobs:
  terraform-plan-airbyte:
    name: 'Terraform Plan Airbyte'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: airbyte_extract_load

      - name: Terraform Plan
        run: terraform plan -out=airbyte_extract_load.tfplan
        working-directory: airbyte_extract_load

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: airbyte_extract_load.tfplan
          path: airbyte_extract_load/airbyte_extract_load.tfplan

  terraform-apply-airbyte:
    name: 'Terraform Apply Airbyte'
    runs-on: ubuntu-latest
    needs: terraform-plan-airbyte
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: airbyte_extract_load.tfplan
          path: airbyte_extract_load

      - name: Terraform Init
        run: terraform init
        working-directory: airbyte_extract_load

      - name: Terraform Apply
        run: terraform apply airbyte_extract_load.tfplan
        working-directory: airbyte_extract_load
